version: '3.6'


services:
  meep-payment-gateway-api:
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__DefaultConnection: 'Host=db-server;Port=1433;Database=client_db;Username=sa;Password=myHardCoreDevDb123@'
      # ASPNETCORE_URLS: 'https://+:7123;http://+:8080'
      # ASPNETCORE_Kestrel__Certificates__Default__Password: 'yourpassword'
      # ASPNETCORE_Kestrel__Certificates__Default__Path: '/https/aspnetapp.pfx'
    ports:
      - "8080:8080" 
      #- "7123:7123"
    # volumes:
    #   - ./https:/https/:ro
    networks:
      - localdev